language: nix

matrix:
  include:
    - os: linux
      script:
        - nix-build tests
    - os: linux
      dist: trusty
      script:
        - nix-build tests
    - os: osx
      script:
        - nix-build tests
