language: nix

script:
 - sudo env NIX_PATH=$NIX_PATH $(which nix-shell) ./support/utils/setup-hydra.fractalide.com.sh
 - [[ $(uname) == Linux ]] && ./support/utils/nix-build-travis-fold.sh --fallback -I fractalide=. release.nix -A rs-tests
 - ./support/utils/nix-build-travis-fold.sh --fallback -I fractalide=. release.nix -A fractalide

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: osx
