language: nix

script:
 - ./support/utils/nix-build-travis-fold.sh -I fractalide=. -A fractalide release.nix

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: osx
