language: nix

script:
 - sudo env NIX_PATH=$NIX_PATH $(which nix-shell) ./support/utils/setup-hydra.fractalide.com.sh
 - sudo env NIX_PATH=$NIX_PATH $(which nix-shell) ./support/utils/setup-sandbox.sh
 - ./support/utils/nix-build-travis-fold.sh -I fractalide=$PWD release.nix

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: osx
